name: Docker push

on:
  push:
    branches:
      - master
      - dev
      - SS-15-application-add-ci-cd
    tags:
      - v*
  pull_request:
    branches:
      - master
      - dev
      - hot-fix
  schedule:
    # re-run monthly to keep image fresh with upstream base images
    - cron: '0 12 15 * *'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: score-sentinel
jobs:
  # This pushes the image to GitHub Packages.
  build-and-push-ghrc-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./portal/gradlew build
      - name: Build image
        run: docker build ./portal --file ./portal/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            my-docker-hub-namespace/my-docker-hub-repository
            ghcr.io/${{ github.repository }}
      - name: Push docker image
        run: docker push ghcr.io/${{ github.actor }}/${{ github.repository }}

